version: '3.9'
services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "aldinokemal2104/go-whatsapp-web-multidevice:latest"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: 'always'
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-wpp-golang.rule=Host(`${DOMAIN_HOST}`)"
      - "traefik.http.routers.api-wpp-golang.entrypoints=websecure"  # Use HTTPS (websecure)
      - "traefik.http.routers.api-wpp-golang.tls.certresolver=myresolver"  # Config. do certificado
      - "traefik.http.services.api-wpp-golang.loadbalancer.server.port=3002"
      - traefik.http.routers.api-wpp-golang.middlewares=myauth

    networks:
      - proxy

networks:
  proxy:
    external: true
